# Generated by Django 4.1.6 on 2023-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=20)),
                ('acct_no', models.IntegerField(max_length=20)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('usr_res_addr', models.CharField(max_length=200)),
                ('usr_off_addr', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(max_length=15)),
                ('acc_bal', models.IntegerField(max_length=12)),
            ],
        ),
    ]
