# Generated by Django 4.1.6 on 2023-02-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('acc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_bal', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('res_addr', models.CharField(max_length=250)),
                ('off_addr', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='acc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.ouruser'),
        ),
    ]
