# Generated by Django 4.1.6 on 2023-02-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_accountdetails_ouruser_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trsn_date', models.DateTimeField(auto_now_add=True)),
                ('trsn_type', models.CharField(max_length=12)),
                ('trsn_amount', models.FloatField()),
                ('trsn_balance', models.FloatField()),
                ('trsn_acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.accountdetails')),
            ],
        ),
    ]
