# Generated by Django 4.1.6 on 2023-02-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_acctransactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccTransactions',
            new_name='AccountTransactions',
        ),
    ]
