# Generated by Django 4.1.6 on 2023-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_ouruser_f_name_alter_ouruser_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='phone_no',
            field=models.CharField(max_length=160),
        ),
    ]
